# Generated by Django 4.1.7 on 2023-04-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_id_usuario_perfil_id_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
        migrations.AddField(
            model_name='post',
            name='userImg',
            field=models.ImageField(default='bpp.webp', upload_to=''),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='profileimg',
            field=models.ImageField(default='bpp.webp', upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='posts/'),
        ),
    ]
