# Generated by Django 4.1.7 on 2023-05-16 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_comentario_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post'),
        ),
    ]
