# Generated by Django 4.1.7 on 2023-05-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_comentario_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='post_id',
            field=models.CharField(max_length=500),
        ),
    ]
